package com.jetbrains.plugin.structure.edu

const val TITLE = "title"
const val TYPE = "type"
const val NAME = "name"
const val SUMMARY = "summary"
const val LANGUAGE = "language"
const val PROGRAMMING_LANGUAGE = "programming_language"
const val ENVIRONMENT = "environment"
const val ITEMS = "items"
const val VENDOR = "vendor"
const val VERSION = "course_version"
const val DESCRIPTOR_VERSION = "version"
const val VENDOR_NAME = "name"
const val VENDOR_EMAIL = "email"
const val VENDOR_URL = "url"
const val TASK_LIST = "task_list"
const val TASK_TYPE = "task_type"