[versions]
commons-fileupload = "1.5"
groovy = "3.0.19"
logback-classic = "1.2.13"
log4j-toSlf4j = "2.22.0"
mapdb = "3.0.10"
spring-boot = "2.7.18"
spring-dependencyManagement = "1.1.7"
teamcity-restClient = "1.14.0"

[libraries]
commons-fileupload = { group = "commons-fileupload", name = "commons-fileupload", version.ref = "commons-fileupload" }
groovy = { group = "org.codehaus.groovy", name = "groovy", version.ref = "groovy" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback-classic" }
log4j-toSlf4j = { group = "org.apache.logging.log4j", name = "log4j-to-slf4j", version.ref = "log4j-toSlf4j" }
mapdb = { group = "org.mapdb", name = "mapdb", version.ref = "mapdb" }
spring-boot-devtools = { group = "org.springframework.boot", name = "spring-boot-devtools", version.ref = "spring-boot" }
spring-boot-starter-actuator = { group = "org.springframework.boot", name = "spring-boot-starter-actuator", version.ref = "spring-boot" }
spring-boot-starter-tomcat = { group = "org.springframework.boot", name = "spring-boot-starter-tomcat", version.ref = "spring-boot" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web", version.ref = "spring-boot" }
teamcity-restClient = { group = "org.jetbrains.teamcity", name = "teamcity-rest-client", version.ref = "teamcity-restClient" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependencyManagement = { id = "io.spring.dependency-management", version.ref = "spring-dependencyManagement" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version = "1.9.21" }
