package com.jetbrains.plugin.structure.teamcity.action

val allowedRunnerToAllowedParams = mapOf(
  "gradle" to setOf(
    "tasks",
    "build-file",
    "incremental",
    "working-directory",
    "gradle-home",
    "gradle-params",
    "use-gradle-wrapper",
    "gradle-wrapper-path",
    "enable-debug",
    "enable-stacktrace",
    "jdk-home",
    "jvm-args",
  ),
  "maven" to setOf(
    "goals",
    "pom-location",
    "runner-arguments",
    "working-directory",
    "path",
    "user-settings-selection",
    "user-settings-path",
    "use-own-local-repo",
    "local-repo-scope",
    "is-incremental",
    "jdk-home",
    "jvm-args",
  ),
  "node-js" to setOf(
    "working-directory",
    "shell-script",
  ),
  "command-line" to setOf(
    "use-custom-script",
    "script-content",
    "working-directory",
    "format-stderr-as-error",
    "path",
    "arguments",
  ),
  "unity" to setOf(
    "working-directory",
    "project-path",
    "execute-method",
    "build-target",
    "build-player",
    "build-player-path",
    "no-graphics",
    "no-quit",
    "arguments",
    "unity-version",
    "unity-root",
    "run-editor-tests",
    "test-platform",
    "test-categories",
    "test-names",
    "silent-crashes",
    "line-statuses-file",
    "log-file-path",
    "verbosity",
    "detection-mode",
    "activate-license",
    "unity-license-scope",
    "unity-license-type",
    "unity-personal-license-content",
    "serial-number",
    "username",
    "password",
    "cache-server",
  ),
)