name: IntelliJ Plugin Structure
on:
  # Trigger the workflow on pushes to only the 'master' branch (this avoids duplicate checks being run e.g. for dependabot pull requests)
  push:
    branches: [master]
    paths: [ 'intellij-plugin-structure/**', '.github/workflows/intellij-plugin-structure.yml' ]
  # Trigger the workflow on any pull request
  pull_request:
    paths: [ 'intellij-plugin-structure/**', '.github/workflows/intellij-plugin-structure.yml' ]

jobs:

  # Run Gradle Wrapper Validation Action to verify the wrapper's checksum
  gradleValidation:
    name: Gradle Wrapper
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v4.1.7

      # Validate wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4

  # Run tests
  test:
    name: Test
    needs: gradleValidation
    runs-on: ubuntu-latest
    steps:

      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v4.1.7

      # Cache Gradle dependencies
      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}

      # Cache Gradle Wrapper
      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      # Run tests
      - name: Run Tests
        run: |
          cd intellij-plugin-structure
          ./gradlew test

      - name: Collect Test Results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results-intellij-plugin-structure
          path: ${{ github.workspace }}/intellij-plugin-structure/build/reports/tests/test/
