name: IntelliJ Feature Extractor
on:
  # Trigger the workflow on pushes to only the 'master' branch (this avoids duplicate checks being run e.g. for dependabot pull requests)
  push:
    branches: [master]
    paths: [ 'intellij-feature-extractor/**', '.github/workflows/intellij-feature-extractor.yml' ]
  # Trigger the workflow on any pull request
  pull_request:
    paths: [ 'intellij-feature-extractor/**', '.github/workflows/intellij-feature-extractor.yml' ]

jobs:

  # Run Gradle Wrapper Validation Action to verify the wrapper's checksum
  gradleValidation:
    name: Gradle Wrapper
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v4.2.2

      # Validate wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v4.2.2

  # Run tests
  test:
    name: Test
    needs: gradleValidation
    runs-on: ubuntu-latest
    steps:

      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v4.2.2

      # Cache Gradle dependencies
      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v4.2.3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}

      # Cache Gradle Wrapper
      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v4.2.3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      # Publish dev lib versions
      - name: Publish Dev Version
        run: |
          cd plugins-verifier-service
          ./gradlew :intellij-plugin-structure:publishToMavenLocal
          ./gradlew :intellij-plugin-verifier:publishToMavenLocal

      # Run tests
      - name: Run Tests
        run: |
          cd intellij-feature-extractor
          ./gradlew test

      - name: Collect Test Results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results-intellij-feature-extractor
          path: ${{ github.workspace }}/intellij-feature-extractor/build/reports/tests/test/
